# Remove this and add `types-redis`
# when the issue https://github.com/python/typeshed/issues/8242 is resolved.
[[tool.mypy.overrides]]
module = ['redis.asyncio']

[tool.black]
exclude = '''
/(
  \.toml
  |\.sh
  |\.git
  |\.ini
  |Dockerfile
  |Jenkinfile
)/
'''
include = '\.pyi?$'
line-length = 88
target-version = ['py39', 'py310', 'py311']
